# Reference here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Enabled: false
  Max: 120

Metrics/MethodLength:
  Description: 'Try to avoid methods longer than 50 lines of code.'
  Enabled: true
  Max: 50

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
