# Reference here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

Metrics/LineLength:
  Description: 'Limit lines to 310 characters.'
  Enabled: true
  Max: 310

Metrics/MethodLength:
  Description: 'Try to avoid methods longer than 50 lines of code.'
  Enabled: true
  Max: 50
